<?php
$title='Powering Your Home. Lighting Your Future.';
require 'includes/header.php';
$cats=$pdo->query("SELECT * FROM categories WHERE active=1 ORDER BY name")->fetchAll();
$products=$pdo->query("SELECT p.*,c.name category FROM products p JOIN categories c ON c.id=p.category_id WHERE p.active=1 AND p.featured=1 ORDER BY p.id DESC LIMIT 8")->fetchAll();
?>
<section class="hero"><div class="container"><div class="row align-items-center"><div class="col-lg-7"><span class="badge bg-success mb-3">POWER • SOLAR • LIGHTING</span><h1>Powering Your Home.<br>Lighting Your Future.</h1><p>Reliable inverter batteries, solar solutions and modern LED lighting for homes and businesses.</p><a class="btn btn-warning btn-lg me-2" href="products.php">Explore Products</a><a class="btn btn-outline-light btn-lg" href="quote.php">Get a Quote</a></div><div class="col-lg-5 mt-4 mt-lg-0"><div class="feature-card p-4 text-dark"><i class="bi bi-sun-fill display-3 text-warning"></i><h3 class="mt-3">Smart Energy Solutions</h3><p class="mb-0">Backup power and efficient lighting in one place.</p></div></div></div></div></section>
<section class="py-5"><div class="container"><h2 class="section-title text-center">Shop by Category</h2><p class="text-center text-muted mb-4">Explore our power and lighting range.</p><div class="row g-4">
<?php foreach($cats as $c): ?><div class="col-sm-6 col-lg-4"><div class="category-card h-100"><img class="w-100" src="<?= e($c['image'] ?: 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=900') ?>"><div class="p-4"><h4><?= e($c['name']) ?></h4><p class="text-muted"><?= e($c['description']) ?></p><a href="category.php?slug=<?= e($c['slug']) ?>" class="btn btn-outline-primary">View Products</a></div></div></div><?php endforeach; ?>
</div></div></section>
<section class="py-5 bg-white"><div class="container"><div class="d-flex justify-content-between align-items-center mb-4"><div><h2 class="section-title">Featured Products</h2><p class="text-muted mb-0">Popular products ready for enquiry.</p></div><a href="products.php">View All</a></div><div class="row g-4"><?php foreach($products as $p): include 'includes/product-card.php'; endforeach; ?></div></div></section>
<section class="py-5"><div class="container"><div class="row g-3"><div class="col-md-4"><div class="feature-card p-4 h-100"><i class="bi bi-shield-check fs-1 text-success"></i><h5>Quality Products</h5><p class="text-muted">Carefully selected power and lighting solutions.</p></div></div><div class="col-md-4"><div class="feature-card p-4 h-100"><i class="bi bi-chat-dots fs-1 text-primary"></i><h5>Expert Guidance</h5><p class="text-muted">Get help choosing the right product for your requirement.</p></div></div><div class="col-md-4"><div class="feature-card p-4 h-100"><i class="bi bi-headset fs-1 text-warning"></i><h5>Customer Support</h5><p class="text-muted">Enquiry and after-sales support for your purchases.</p></div></div></div></div></section>
<a class="btn btn-success whatsapp rounded-pill px-4" target="_blank" href="https://wa.me/"><i class="bi bi-whatsapp"></i> WhatsApp</a>
<?php require 'includes/footer.php'; ?>